### ISSUE TITLE
datasets

### ISSUE THREAD

**Issue by phj123456789** [ridgerchu/TCJA#2]
Hello author, thank you very much for sharing the code. May I ask how these three datasets were obtained? After downloading them myself, I still reported an error, or could you please share the datasets? Looking forward to your reply. Thank you.

**Comment by ridgerchu** [comment]
Hi, sorry for the late reply. I have the datasets that have been pre-split to T=14(NCAL 101) and T=20(DVSGesture), for the CIFAR10-DVS, I only have the dataset for the TET version, please use it when you try to use TCJA-TET. here are download link for the three datsets:
NCAL101: url: https://pan.baidu.com/s/1X-10X6Icb4upe0tY9BKnxg code: 1234 
CIFAR10DVS: url: https://pan.baidu.com/s/1qxj_Il0rVi8Xt-GgjdmaMA code: 1234
DVSGesture: url:  https://pan.baidu.com/s/1uLN_BGjPvF-Lrg84qMYpdA code: 1234
Hope it can help!

**Comment by phj123456789** [comment]
> 

非常感谢您的回复
