### ISSUE TITLE
Fashion-MNIST

### ISSUE THREAD

**Issue by phj123456789** [ridgerchu/TCJA#5]
作者您好，请问您论文里写的用TCJA-SNN方法来测试Fashion-MNIST数据集的实验，在代码中还有吗，没有在代码中找到，期待您的回复。

**Comment by ridgerchu** [comment]
你好，对不起因为通知问题一直没有通知到这个repo上，没有及时回复，这里的FashionMNIST直接采用SpikingJelly的官方示例FashionMNIST加上TCJA就可以了，https://github.com/fangwei123456/spikingjelly/blob/0.0.0.0.12/spikingjelly/clock_driven/examples/conv_fashion_mnist.py，注意在卷积结构上可能需要修改一点。

**Comment by phj123456789** [comment]
好嘞，谢谢您的回复
