### ISSUE TITLE
Cifar10dvs 精度问题

### ISSUE THREAD

**Issue by stephencoding** [ridgerchu/TCJA#8]
您好作者，在跑您的代码的时候，我发现我的cifar10dvs只有0.785的准确率，然后我的epoch设置是300，不知道是不是因为论文中数据增强的原因导致精度问题，如果数据增强是代码中的dvs_aug，我打断点也发现有使用到，所以我想问还有什么问题导致精度问题，还有作者您的epoch设置是多少应该，我做实验看cifar10dvs在300以内就已经收敛了，但是不知道更大的epoch还有没有可能提高精度，我虚心的请教以上问题。

**Comment by ridgerchu** [comment]
你好！我对CIFAR10DVS和其他数据集的Epoch均设置为1000，这一设计遵循了Wei Fang 的文章Incorporating Learnable Membrane Time Constant to Enhance Learning of Spiking Neural Networks。在CIFAR10DVS的设计上，默认是采用的非TET，这一结构可能需要更多的epoch以收敛；在tet文件夹中，你可以根据[TET github repo](https://github.com/brain-intelligence-lab/temporal_efficient_training)内的方式启动TET训练，其的精度与收敛速度会更快.

**Comment by stephencoding** [comment]
非常感谢作者！
